default_config:

logger:
#  default: info
  default: warning
  logs:
    custom_components.met_local_forecast: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
#  start: true
#  wait: false