name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Pack the Met.no next 6 hours forecast dir as a zip and upload to the release
      - name: ZIP Met.no next 6 hours forecast Dir
        run: |
          cd ${{ github.workspace }}/custom_components/met_next_6_hours_forecast
          zip home-assistant-met-next-6-hours-forecast.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/met_next_6_hours_forecast/home-assistant-met-next-6-hours-forecast.zip
          asset_name: home-assistant-met-next-6-hours-forecast.zip
          tag: ${{ github.ref }}
          overwrite: true
